# diet/management/commands/init_food_data.py

from django.core.management.base import BaseCommand
from diet.models import FoodItem


class Command(BaseCommand):
    help = '初始化食物数据库'

    def handle(self, *args, **options):
        foods_data = [
            # ============ 主食类 ============
            {'name': '米饭', 'category': '主食', 'calories': 116, 'protein': 2.6, 'carbohydrates': 25.9, 'fat': 0.3},
            {'name': '糙米饭', 'category': '主食', 'calories': 111, 'protein': 2.6, 'carbohydrates': 23.5, 'fat': 0.9},
            {'name': '馒头', 'category': '主食', 'calories': 221, 'protein': 7.0, 'carbohydrates': 47.0, 'fat': 1.1},
            {'name': '面条', 'category': '主食', 'calories': 137, 'protein': 4.5, 'carbohydrates': 28.0, 'fat': 0.5},
            {'name': '挂面', 'category': '主食', 'calories': 346, 'protein': 11.0, 'carbohydrates': 73.0, 'fat': 1.2},
            {'name': '乌冬面', 'category': '主食', 'calories': 136, 'protein': 2.6, 'carbohydrates': 29.0, 'fat': 0.5},
            {'name': '意大利面', 'category': '主食', 'calories': 371, 'protein': 13.0, 'carbohydrates': 75.0, 'fat': 1.5},
            {'name': '面包', 'category': '主食', 'calories': 265, 'protein': 8.3, 'carbohydrates': 50.0, 'fat': 3.3},
            {'name': '全麦面包', 'category': '主食', 'calories': 246, 'protein': 9.2, 'carbohydrates': 46.0, 'fat': 3.5},
            {'name': '燕麦', 'category': '主食', 'calories': 367, 'protein': 15.0, 'carbohydrates': 66.0, 'fat': 6.7},
            {'name': '燕麦片', 'category': '主食', 'calories': 338, 'protein': 10.1, 'carbohydrates': 69.3, 'fat': 2.5},
            {'name': '小米', 'category': '主食', 'calories': 358, 'protein': 9.0, 'carbohydrates': 75.1, 'fat': 3.1},
            {'name': '黑米', 'category': '主食', 'calories': 341, 'protein': 8.5, 'carbohydrates': 72.2, 'fat': 2.0},
            {'name': '玉米', 'category': '主食', 'calories': 106, 'protein': 4.0, 'carbohydrates': 22.8, 'fat': 1.2},
            {'name': '红薯', 'category': '主食', 'calories': 99, 'protein': 1.1, 'carbohydrates': 24.7, 'fat': 0.2},
            {'name': '紫薯', 'category': '主食', 'calories': 82, 'protein': 1.5, 'carbohydrates': 20.0, 'fat': 0.2},
            {'name': '土豆', 'category': '主食', 'calories': 76, 'protein': 2.0, 'carbohydrates': 17.2, 'fat': 0.2},
            {'name': '山药', 'category': '主食', 'calories': 56, 'protein': 1.9, 'carbohydrates': 12.4, 'fat': 0.2},
            {'name': '南瓜', 'category': '主食', 'calories': 22, 'protein': 0.7, 'carbohydrates': 5.3, 'fat': 0.1},
            {'name': '意大利饺子', 'category': '主食', 'calories': 131, 'protein': 4.4, 'carbohydrates': 22.0, 'fat': 2.7},
            {'name': '包子', 'category': '主食', 'calories': 227, 'protein': 6.4, 'carbohydrates': 43.8, 'fat': 2.8},
            {'name': '饺子', 'category': '主食', 'calories': 198, 'protein': 7.9, 'carbohydrates': 26.5, 'fat': 6.7},

            # ============ 肉类 ============
            {'name': '鸡胸肉', 'category': '肉类', 'calories': 133, 'protein': 19.4, 'carbohydrates': 2.5, 'fat': 5.0},
            {'name': '鸡腿肉', 'category': '肉类', 'calories': 181, 'protein': 16.0, 'carbohydrates': 0, 'fat': 13.0},
            {'name': '鸡翅', 'category': '肉类', 'calories': 194, 'protein': 17.4, 'carbohydrates': 0, 'fat': 13.6},
            {'name': '猪瘦肉', 'category': '肉类', 'calories': 143, 'protein': 20.3, 'carbohydrates': 0, 'fat': 6.2},
            {'name': '猪肉', 'category': '肉类', 'calories': 395, 'protein': 13.2, 'carbohydrates': 0, 'fat': 37.0},
            {'name': '猪排骨', 'category': '肉类', 'calories': 278, 'protein': 18.0, 'carbohydrates': 0, 'fat': 23.1},
            {'name': '猪肝', 'category': '肉类', 'calories': 129, 'protein': 19.3, 'carbohydrates': 5.0, 'fat': 3.5},
            {'name': '牛肉', 'category': '肉类', 'calories': 125, 'protein': 20.0, 'carbohydrates': 0, 'fat': 4.2},
            {'name': '牛腱子', 'category': '肉类', 'calories': 106, 'protein': 20.2, 'carbohydrates': 0, 'fat': 2.3},
            {'name': '牛排', 'category': '肉类', 'calories': 271, 'protein': 17.8, 'carbohydrates': 0, 'fat': 22.0},
            {'name': '羊肉', 'category': '肉类', 'calories': 203, 'protein': 19.0, 'carbohydrates': 0, 'fat': 14.1},
            {'name': '鸭肉', 'category': '肉类', 'calories': 240, 'protein': 15.5, 'carbohydrates': 0, 'fat': 19.7},
            {'name': '鹅肉', 'category': '肉类', 'calories': 251, 'protein': 17.9, 'carbohydrates': 0, 'fat': 19.9},

            # ============ 水产类 ============
            {'name': '鱼肉', 'category': '水产', 'calories': 104, 'protein': 17.6, 'carbohydrates': 0, 'fat': 3.7},
            {'name': '三文鱼', 'category': '水产', 'calories': 139, 'protein': 20.0, 'carbohydrates': 0, 'fat': 6.3},
            {'name': '鲈鱼', 'category': '水产', 'calories': 105, 'protein': 18.6, 'carbohydrates': 0, 'fat': 3.1},
            {'name': '鲫鱼', 'category': '水产', 'calories': 108, 'protein': 17.1, 'carbohydrates': 0, 'fat': 4.1},
            {'name': '草鱼', 'category': '水产', 'calories': 113, 'protein': 16.6, 'carbohydrates': 0, 'fat': 5.2},
            {'name': '带鱼', 'category': '水产', 'calories': 127, 'protein': 17.7, 'carbohydrates': 0, 'fat': 4.9},
            {'name': '金枪鱼', 'category': '水产', 'calories': 99, 'protein': 23.3, 'carbohydrates': 0, 'fat': 0.6},
            {'name': '鳕鱼', 'category': '水产', 'calories': 88, 'protein': 20.4, 'carbohydrates': 0, 'fat': 0.8},
            {'name': '虾仁', 'category': '水产', 'calories': 87, 'protein': 18.6, 'carbohydrates': 2.8, 'fat': 0.8},
            {'name': '大虾', 'category': '水产', 'calories': 93, 'protein': 18.6, 'carbohydrates': 2.8, 'fat': 1.2},
            {'name': '螃蟹', 'category': '水产', 'calories': 95, 'protein': 17.5, 'carbohydrates': 2.3, 'fat': 2.6},
            {'name': '鱿鱼', 'category': '水产', 'calories': 75, 'protein': 15.2, 'carbohydrates': 3.8, 'fat': 0.8},
            {'name': '章鱼', 'category': '水产', 'calories': 52, 'protein': 10.6, 'carbohydrates': 1.4, 'fat': 0.8},
            {'name': '扇贝', 'category': '水产', 'calories': 60, 'protein': 11.1, 'carbohydrates': 2.6, 'fat': 0.6},
            {'name': '生蚝', 'category': '水产', 'calories': 57, 'protein': 9.0, 'carbohydrates': 4.3, 'fat': 1.0},

            # ============ 蔬菜类 ============
            {'name': '西兰花', 'category': '蔬菜', 'calories': 36, 'protein': 4.1, 'carbohydrates': 4.3, 'fat': 0.6},
            {'name': '花椰菜', 'category': '蔬菜', 'calories': 24, 'protein': 2.1, 'carbohydrates': 4.6, 'fat': 0.2},
            {'name': '番茄', 'category': '蔬菜', 'calories': 15, 'protein': 0.9, 'carbohydrates': 3.3, 'fat': 0.2},
            {'name': '圣女果', 'category': '蔬菜', 'calories': 22, 'protein': 1.0, 'carbohydrates': 4.9, 'fat': 0.2},
            {'name': '黄瓜', 'category': '蔬菜', 'calories': 15, 'protein': 0.8, 'carbohydrates': 2.9, 'fat': 0.2},
            {'name': '胡萝卜', 'category': '蔬菜', 'calories': 25, 'protein': 1.0, 'carbohydrates': 6.0, 'fat': 0.2},
            {'name': '菠菜', 'category': '蔬菜', 'calories': 28, 'protein': 2.6, 'carbohydrates': 4.5, 'fat': 0.3},
            {'name': '白菜', 'category': '蔬菜', 'calories': 17, 'protein': 1.5, 'carbohydrates': 3.2, 'fat': 0.2},
            {'name': '大白菜', 'category': '蔬菜', 'calories': 13, 'protein': 1.1, 'carbohydrates': 2.4, 'fat': 0.2},
            {'name': '芹菜', 'category': '蔬菜', 'calories': 14, 'protein': 0.8, 'carbohydrates': 2.6, 'fat': 0.1},
            {'name': '生菜', 'category': '蔬菜', 'calories': 13, 'protein': 0.8, 'carbohydrates': 2.1, 'fat': 0.3},
            {'name': '油菜', 'category': '蔬菜', 'calories': 15, 'protein': 1.8, 'carbohydrates': 2.0, 'fat': 0.5},
            {'name': '茄子', 'category': '蔬菜', 'calories': 21, 'protein': 1.1, 'carbohydrates': 4.9, 'fat': 0.2},
            {'name': '青椒', 'category': '蔬菜', 'calories': 22, 'protein': 1.0, 'carbohydrates': 5.3, 'fat': 0.2},
            {'name': '彩椒', 'category': '蔬菜', 'calories': 26, 'protein': 0.9, 'carbohydrates': 6.3, 'fat': 0.2},
            {'name': '洋葱', 'category': '蔬菜', 'calories': 39, 'protein': 1.1, 'carbohydrates': 9.0, 'fat': 0.1},
            {'name': '蒜苗', 'category': '蔬菜', 'calories': 37, 'protein': 2.1, 'carbohydrates': 8.0, 'fat': 0.1},
            {'name': '韭菜', 'category': '蔬菜', 'calories': 26, 'protein': 2.4, 'carbohydrates': 4.6, 'fat': 0.5},
            {'name': '豆芽', 'category': '蔬菜', 'calories': 18, 'protein': 2.1, 'carbohydrates': 2.7, 'fat': 0.1},
            {'name': '豆角', 'category': '蔬菜', 'calories': 28, 'protein': 2.7, 'carbohydrates': 5.7, 'fat': 0.2},
            {'name': '四季豆', 'category': '蔬菜', 'calories': 30, 'protein': 2.4, 'carbohydrates': 6.2, 'fat': 0.1},
            {'name': '毛豆', 'category': '蔬菜', 'calories': 123, 'protein': 13.1, 'carbohydrates': 10.5, 'fat': 5.0},
            {'name': '芦笋', 'category': '蔬菜', 'calories': 19, 'protein': 2.2, 'carbohydrates': 3.9, 'fat': 0.1},
            {'name': '竹笋', 'category': '蔬菜', 'calories': 19, 'protein': 2.6, 'carbohydrates': 3.6, 'fat': 0.2},
            {'name': '蘑菇', 'category': '蔬菜', 'calories': 20, 'protein': 2.9, 'carbohydrates': 3.3, 'fat': 0.3},
            {'name': '香菇', 'category': '蔬菜', 'calories': 19, 'protein': 2.2, 'carbohydrates': 5.2, 'fat': 0.3},
            {'name': '金针菇', 'category': '蔬菜', 'calories': 26, 'protein': 2.4, 'carbohydrates': 6.0, 'fat': 0.2},
            {'name': '木耳', 'category': '蔬菜', 'calories': 27, 'protein': 1.5, 'carbohydrates': 6.5, 'fat': 0.2},
            {'name': '银耳', 'category': '蔬菜', 'calories': 200, 'protein': 10.0, 'carbohydrates': 67.3, 'fat': 1.4},
            {'name': '海带', 'category': '蔬菜', 'calories': 12, 'protein': 1.2, 'carbohydrates': 2.1, 'fat': 0.1},
            {'name': '紫菜', 'category': '蔬菜', 'calories': 207, 'protein': 26.7, 'carbohydrates': 44.1, 'fat': 1.1},

            # ============ 水果类 ============
            {'name': '苹果', 'category': '水果', 'calories': 54, 'protein': 0.2, 'carbohydrates': 13.5, 'fat': 0.2},
            {'name': '香蕉', 'category': '水果', 'calories': 93, 'protein': 1.2, 'carbohydrates': 22.0, 'fat': 0.2},
            {'name': '橙子', 'category': '水果', 'calories': 48, 'protein': 0.8, 'carbohydrates': 11.8, 'fat': 0.2},
            {'name': '橘子', 'category': '水果', 'calories': 44, 'protein': 0.8, 'carbohydrates': 10.5, 'fat': 0.2},
            {'name': '柚子', 'category': '水果', 'calories': 42, 'protein': 0.8, 'carbohydrates': 10.5, 'fat': 0.2},
            {'name': '葡萄', 'category': '水果', 'calories': 69, 'protein': 0.4, 'carbohydrates': 17.0, 'fat': 0.4},
            {'name': '西瓜', 'category': '水果', 'calories': 25, 'protein': 0.6, 'carbohydrates': 5.8, 'fat': 0.1},
            {'name': '哈密瓜', 'category': '水果', 'calories': 34, 'protein': 0.5, 'carbohydrates': 7.9, 'fat': 0.1},
            {'name': '草莓', 'category': '水果', 'calories': 30, 'protein': 1.0, 'carbohydrates': 7.1, 'fat': 0.2},
            {'name': '蓝莓', 'category': '水果', 'calories': 57, 'protein': 0.7, 'carbohydrates': 14.5, 'fat': 0.3},
            {'name': '樱桃', 'category': '水果', 'calories': 46, 'protein': 1.0, 'carbohydrates': 10.2, 'fat': 0.3},
            {'name': '桃子', 'category': '水果', 'calories': 42, 'protein': 0.9, 'carbohydrates': 10.1, 'fat': 0.1},
            {'name': '梨', 'category': '水果', 'calories': 44, 'protein': 0.4, 'carbohydrates': 11.3, 'fat': 0.2},
            {'name': '猕猴桃', 'category': '水果', 'calories': 56, 'protein': 0.8, 'carbohydrates': 14.5, 'fat': 0.6},
            {'name': '芒果', 'category': '水果', 'calories': 35, 'protein': 0.6, 'carbohydrates': 8.3, 'fat': 0.2},
            {'name': '菠萝', 'category': '水果', 'calories': 44, 'protein': 0.5, 'carbohydrates': 10.8, 'fat': 0.1},
            {'name': '火龙果', 'category': '水果', 'calories': 51, 'protein': 1.1, 'carbohydrates': 13.3, 'fat': 0.2},
            {'name': '荔枝', 'category': '水果', 'calories': 70, 'protein': 0.9, 'carbohydrates': 16.6, 'fat': 0.2},
            {'name': '龙眼', 'category': '水果', 'calories': 71, 'protein': 1.2, 'carbohydrates': 16.2, 'fat': 0.1},
            {'name': '柿子', 'category': '水果', 'calories': 74, 'protein': 0.4, 'carbohydrates': 18.5, 'fat': 0.1},
            {'name': '石榴', 'category': '水果', 'calories': 63, 'protein': 0.9, 'carbohydrates': 14.5, 'fat': 0.2},
            {'name': '木瓜', 'category': '水果', 'calories': 29, 'protein': 0.4, 'carbohydrates': 7.2, 'fat': 0.1},
            {'name': '柠檬', 'category': '水果', 'calories': 35, 'protein': 1.1, 'carbohydrates': 9.3, 'fat': 0.3},

            # ============ 蛋奶类 ============
            {'name': '鸡蛋', 'category': '蛋奶', 'calories': 147, 'protein': 13.3, 'carbohydrates': 2.8, 'fat': 8.8},
            {'name': '鸭蛋', 'category': '蛋奶', 'calories': 180, 'protein': 12.6, 'carbohydrates': 3.1, 'fat': 13.0},
            {'name': '鹅蛋', 'category': '蛋奶', 'calories': 196, 'protein': 11.1, 'carbohydrates': 2.8, 'fat': 15.6},
            {'name': '鹌鹑蛋', 'category': '蛋奶', 'calories': 160, 'protein': 12.8, 'carbohydrates': 2.1, 'fat': 11.1},
            {'name': '咸鸭蛋', 'category': '蛋奶', 'calories': 190, 'protein': 12.7, 'carbohydrates': 4.7, 'fat': 12.7},
            {'name': '皮蛋', 'category': '蛋奶', 'calories': 171, 'protein': 14.2, 'carbohydrates': 4.5, 'fat': 10.7},
            {'name': '牛奶', 'category': '蛋奶', 'calories': 54, 'protein': 3.0, 'carbohydrates': 3.4, 'fat': 3.2},
            {'name': '脱脂牛奶', 'category': '蛋奶', 'calories': 35, 'protein': 3.4, 'carbohydrates': 5.0, 'fat': 0.1},
            {'name': '全脂牛奶', 'category': '蛋奶', 'calories': 66, 'protein': 3.3, 'carbohydrates': 5.0, 'fat': 3.7},
            {'name': '酸奶', 'category': '蛋奶', 'calories': 72, 'protein': 2.5, 'carbohydrates': 9.3, 'fat': 2.7},
            {'name': '希腊酸奶', 'category': '蛋奶', 'calories': 97, 'protein': 10.0, 'carbohydrates': 3.6, 'fat': 5.0},
            {'name': '豆浆', 'category': '蛋奶', 'calories': 31, 'protein': 1.8, 'carbohydrates': 1.1, 'fat': 1.8},
            {'name': '奶酪', 'category': '蛋奶', 'calories': 328, 'protein': 25.7, 'carbohydrates': 3.5, 'fat': 23.5},
            {'name': '黄油', 'category': '蛋奶', 'calories': 717, 'protein': 1.4, 'carbohydrates': 2.8, 'fat': 81.1},
            {'name': '奶油', 'category': '蛋奶', 'calories': 309, 'protein': 2.1, 'carbohydrates': 3.4, 'fat': 33.0},

            # ============ 豆制品 ============
            {'name': '豆腐', 'category': '豆制品', 'calories': 81, 'protein': 8.1, 'carbohydrates': 4.2, 'fat': 3.7},
            {'name': '豆干', 'category': '豆制品', 'calories': 140, 'protein': 16.2, 'carbohydrates': 4.7, 'fat': 6.0},
            {'name': '豆皮', 'category': '豆制品', 'calories': 409, 'protein': 44.6, 'carbohydrates': 18.8, 'fat': 17.4},
            {'name': '腐竹', 'category': '豆制品', 'calories': 459, 'protein': 44.6, 'carbohydrates': 22.3, 'fat': 21.7},
            {'name': '豆腐脑', 'category': '豆制品', 'calories': 15, 'protein': 1.9, 'carbohydrates': 0.8, 'fat': 0.8},
            {'name': '内酯豆腐', 'category': '豆制品', 'calories': 49, 'protein': 5.0, 'carbohydrates': 2.4, 'fat': 2.5},
            {'name': '豆腐丝', 'category': '豆制品', 'calories': 201, 'protein': 21.5, 'carbohydrates': 3.5, 'fat': 12.3},
            {'name': '黄豆', 'category': '豆制品', 'calories': 359, 'protein': 35.0, 'carbohydrates': 34.2, 'fat': 16.0},
            {'name': '黑豆', 'category': '豆制品', 'calories': 381, 'protein': 36.0, 'carbohydrates': 33.6, 'fat': 15.9},
            {'name': '绿豆', 'category': '豆制品', 'calories': 316, 'protein': 21.6, 'carbohydrates': 62.0, 'fat': 0.8},
            {'name': '红豆', 'category': '豆制品', 'calories': 324, 'protein': 20.2, 'carbohydrates': 63.4, 'fat': 0.6},

            # ============ 坚果类 ============
            {'name': '核桃', 'category': '坚果', 'calories': 654, 'protein': 15.0, 'carbohydrates': 13.7, 'fat': 65.2},
            {'name': '杏仁', 'category': '坚果', 'calories': 578, 'protein': 21.0, 'carbohydrates': 22.0, 'fat': 50.0},
            {'name': '腰果', 'category': '坚果', 'calories': 552, 'protein': 17.3, 'carbohydrates': 41.0, 'fat': 36.7},
            {'name': '开心果', 'category': '坚果', 'calories': 614, 'protein': 20.0, 'carbohydrates': 28.0, 'fat': 53.0},
            {'name': '花生', 'category': '坚果', 'calories': 574, 'protein': 24.8, 'carbohydrates': 21.7, 'fat': 48.0},
            {'name': '瓜子', 'category': '坚果', 'calories': 606, 'protein': 23.9, 'carbohydrates': 13.1, 'fat': 53.4},
            {'name': '松子', 'category': '坚果', 'calories': 640, 'protein': 13.7, 'carbohydrates': 19.3, 'fat': 63.5},
            {'name': '榛子', 'category': '坚果', 'calories': 617, 'protein': 13.7, 'carbohydrates': 16.7, 'fat': 60.5},
            {'name': '夏威夷果', 'category': '坚果', 'calories': 718, 'protein': 7.9, 'carbohydrates': 13.8, 'fat': 75.8},
            {'name': '碧根果', 'category': '坚果', 'calories': 670, 'protein': 9.2, 'carbohydrates': 14.8, 'fat': 70.1},
            {'name': '巴旦木', 'category': '坚果', 'calories': 600, 'protein': 22.0, 'carbohydrates': 19.6, 'fat': 50.6},

            # ============ 油脂调味品 ============
            {'name': '食用油', 'category': '油脂', 'calories': 899, 'protein': 0, 'carbohydrates': 0, 'fat': 99.9},
            {'name': '橄榄油', 'category': '油脂', 'calories': 899, 'protein': 0, 'carbohydrates': 0, 'fat': 100.0},
            {'name': '花生油', 'category': '油脂', 'calories': 899, 'protein': 0, 'carbohydrates': 0, 'fat': 99.9},
            {'name': '芝麻油', 'category': '油脂', 'calories': 898, 'protein': 0, 'carbohydrates': 0, 'fat': 99.7},
            {'name': '玉米油', 'category': '油脂', 'calories': 899, 'protein': 0, 'carbohydrates': 0, 'fat': 99.9},
            {'name': '猪油', 'category': '油脂', 'calories': 897, 'protein': 0.2, 'carbohydrates': 0, 'fat': 99.6},

            # ============ 饮料零食 ============
            {'name': '可乐', 'category': '饮料', 'calories': 43, 'protein': 0, 'carbohydrates': 10.6, 'fat': 0},
            {'name': '雪碧', 'category': '饮料', 'calories': 42, 'protein': 0, 'carbohydrates': 10.2, 'fat': 0},
            {'name': '橙汁', 'category': '饮料', 'calories': 45, 'protein': 0.7, 'carbohydrates': 10.4, 'fat': 0.2},
            {'name': '苹果汁', 'category': '饮料', 'calories': 46, 'protein': 0.1, 'carbohydrates': 11.3, 'fat': 0.1},
            {'name': '豆奶', 'category': '饮料', 'calories': 54, 'protein': 2.9, 'carbohydrates': 5.6, 'fat': 2.1},
            {'name': '咖啡', 'category': '饮料', 'calories': 1, 'protein': 0.1, 'carbohydrates': 0, 'fat': 0},
            {'name': '拿铁', 'category': '饮料', 'calories': 61, 'protein': 3.2, 'carbohydrates': 5.0, 'fat': 3.2},
            {'name': '绿茶', 'category': '饮料', 'calories': 0, 'protein': 0, 'carbohydrates': 0, 'fat': 0},
            {'name': '红茶', 'category': '饮料', 'calories': 0, 'protein': 0.1, 'carbohydrates': 0.3, 'fat': 0},
            {'name': '薯片', 'category': '零食', 'calories': 548, 'protein': 5.5, 'carbohydrates': 49.2, 'fat': 37.6},
            {'name': '爆米花', 'category': '零食', 'calories': 387, 'protein': 12.6, 'carbohydrates': 77.8, 'fat': 4.3},
            {'name': '饼干', 'category': '零食', 'calories': 433, 'protein': 6.1, 'carbohydrates': 76.2, 'fat': 11.6},
            {'name': '巧克力', 'category': '零食', 'calories': 589, 'protein': 4.3, 'carbohydrates': 51.9, 'fat': 40.1},
            {'name': '冰淇淋', 'category': '零食', 'calories': 207, 'protein': 3.5, 'carbohydrates': 23.6, 'fat': 11.0},

            # ============ 更多主食 ============
            {'name': '年糕', 'category': '主食', 'calories': 154, 'protein': 3.3, 'carbohydrates': 34.7, 'fat': 0.6},
            {'name': '米粉', 'category': '主食', 'calories': 346, 'protein': 7.3, 'carbohydrates': 77.5, 'fat': 1.0},
            {'name': '河粉', 'category': '主食', 'calories': 109, 'protein': 1.9, 'carbohydrates': 25.0, 'fat': 0.3},
            {'name': '凉皮', 'category': '主食', 'calories': 117, 'protein': 3.8, 'carbohydrates': 25.1, 'fat': 0.1},
            {'name': '粉条', 'category': '主食', 'calories': 337, 'protein': 0.5, 'carbohydrates': 84.2, 'fat': 0.1},
            {'name': '粉丝', 'category': '主食', 'calories': 335, 'protein': 0.2, 'carbohydrates': 84.0, 'fat': 0.1},
            {'name': '春卷皮', 'category': '主食', 'calories': 308, 'protein': 8.5, 'carbohydrates': 63.9, 'fat': 1.9},
            {'name': '锅贴', 'category': '主食', 'calories': 230, 'protein': 7.0, 'carbohydrates': 30.5, 'fat': 9.0},
            {'name': '烧麦', 'category': '主食', 'calories': 238, 'protein': 6.8, 'carbohydrates': 28.9, 'fat': 10.5},
            {'name': '汤圆', 'category': '主食', 'calories': 311, 'protein': 4.8, 'carbohydrates': 51.8, 'fat': 9.3},
            {'name': '粽子', 'category': '主食', 'calories': 195, 'protein': 4.1, 'carbohydrates': 41.0, 'fat': 1.6},
            {'name': '花卷', 'category': '主食', 'calories': 203, 'protein': 6.1, 'carbohydrates': 42.3, 'fat': 1.2},
            {'name': '油条', 'category': '主食', 'calories': 386, 'protein': 6.9, 'carbohydrates': 51.0, 'fat': 17.6},
            {'name': '煎饼', 'category': '主食', 'calories': 336, 'protein': 9.1, 'carbohydrates': 49.8, 'fat': 11.6},
            {'name': '麻花', 'category': '主食', 'calories': 524, 'protein': 7.8, 'carbohydrates': 52.8, 'fat': 30.5},
            {'name': '麦片', 'category': '主食', 'calories': 367, 'protein': 12.0, 'carbohydrates': 64.0, 'fat': 7.2},
            {'name': '藜麦', 'category': '主食', 'calories': 368, 'protein': 14.1, 'carbohydrates': 64.2, 'fat': 6.1},
            {'name': '荞麦', 'category': '主食', 'calories': 324, 'protein': 9.3, 'carbohydrates': 71.5, 'fat': 2.3},

            # ============ 更多肉类及加工肉制品 ============
            {'name': '鸡爪', 'category': '肉类', 'calories': 254, 'protein': 23.9, 'carbohydrates': 2.7, 'fat': 16.4},
            {'name': '鸡心', 'category': '肉类', 'calories': 172, 'protein': 15.9, 'carbohydrates': 7.0, 'fat': 9.3},
            {'name': '鸡胗', 'category': '肉类', 'calories': 118, 'protein': 19.2, 'carbohydrates': 4.0, 'fat': 2.8},
            {'name': '猪蹄', 'category': '肉类', 'calories': 260, 'protein': 23.6, 'carbohydrates': 0, 'fat': 18.8},
            {'name': '猪大肠', 'category': '肉类', 'calories': 165, 'protein': 15.8, 'carbohydrates': 0, 'fat': 11.7},
            {'name': '猪肚', 'category': '肉类', 'calories': 110, 'protein': 15.2, 'carbohydrates': 0, 'fat': 5.5},
            {'name': '猪腰', 'category': '肉类', 'calories': 96, 'protein': 15.4, 'carbohydrates': 2.6, 'fat': 2.8},
            {'name': '牛肚', 'category': '肉类', 'calories': 72, 'protein': 14.5, 'carbohydrates': 0, 'fat': 1.6},
            {'name': '牛舌', 'category': '肉类', 'calories': 196, 'protein': 14.9, 'carbohydrates': 0, 'fat': 15.0},
            {'name': '培根', 'category': '肉类', 'calories': 541, 'protein': 8.8, 'carbohydrates': 4.0, 'fat': 54.0},
            {'name': '火腿', 'category': '肉类', 'calories': 330, 'protein': 13.0, 'carbohydrates': 3.8, 'fat': 30.0},
            {'name': '香肠', 'category': '肉类', 'calories': 508, 'protein': 24.1, 'carbohydrates': 11.2, 'fat': 40.7},
            {'name': '午餐肉', 'category': '肉类', 'calories': 229, 'protein': 12.5, 'carbohydrates': 5.0, 'fat': 17.8},
            {'name': '肉松', 'category': '肉类', 'calories': 396, 'protein': 41.8, 'carbohydrates': 10.2, 'fat': 20.2},
            {'name': '鸭脖', 'category': '肉类', 'calories': 178, 'protein': 15.5, 'carbohydrates': 4.1, 'fat': 11.0},

            # ============ 更多水产 ============
            {'name': '黄鱼', 'category': '水产', 'calories': 99, 'protein': 17.9, 'carbohydrates': 0, 'fat': 3.0},
            {'name': '鲳鱼', 'category': '水产', 'calories': 140, 'protein': 18.5, 'carbohydrates': 0, 'fat': 7.3},
            {'name': '鲅鱼', 'category': '水产', 'calories': 121, 'protein': 21.2, 'carbohydrates': 0, 'fat': 3.1},
            {'name': '秋刀鱼', 'category': '水产', 'calories': 310, 'protein': 18.1, 'carbohydrates': 0, 'fat': 26.0},
            {'name': '龙虾', 'category': '水产', 'calories': 90, 'protein': 18.9, 'carbohydrates': 1.3, 'fat': 1.0},
            {'name': '对虾', 'category': '水产', 'calories': 79, 'protein': 16.4, 'carbohydrates': 2.8, 'fat': 0.6},
            {'name': '皮皮虾', 'category': '水产', 'calories': 101, 'protein': 16.8, 'carbohydrates': 3.9, 'fat': 2.0},
            {'name': '基围虾', 'category': '水产', 'calories': 81, 'protein': 16.8, 'carbohydrates': 2.8, 'fat': 1.0},
            {'name': '龙利鱼', 'category': '水产', 'calories': 88, 'protein': 17.1, 'carbohydrates': 0, 'fat': 1.9},
            {'name': '巴沙鱼', 'category': '水产', 'calories': 89, 'protein': 18.8, 'carbohydrates': 0, 'fat': 1.5},
            {'name': '鱼丸', 'category': '水产', 'calories': 107, 'protein': 12.7, 'carbohydrates': 9.3, 'fat': 2.0},
            {'name': '蟹棒', 'category': '水产', 'calories': 90, 'protein': 7.6, 'carbohydrates': 12.6, 'fat': 0.5},
            {'name': '海参', 'category': '水产', 'calories': 78, 'protein': 16.5, 'carbohydrates': 2.5, 'fat': 0.2},
            {'name': '鱿鱼丝', 'category': '水产', 'calories': 313, 'protein': 30.3, 'carbohydrates': 31.5, 'fat': 3.1},

            # ============ 更多蔬菜 ============
            {'name': '娃娃菜', 'category': '蔬菜', 'calories': 11, 'protein': 1.0, 'carbohydrates': 2.0, 'fat': 0.1},
            {'name': '苦瓜', 'category': '蔬菜', 'calories': 19, 'protein': 1.0, 'carbohydrates': 4.9, 'fat': 0.1},
            {'name': '丝瓜', 'category': '蔬菜', 'calories': 20, 'protein': 1.0, 'carbohydrates': 4.9, 'fat': 0.2},
            {'name': '冬瓜', 'category': '蔬菜', 'calories': 11, 'protein': 0.4, 'carbohydrates': 2.6, 'fat': 0.2},
            {'name': '西葫芦', 'category': '蔬菜', 'calories': 18, 'protein': 0.8, 'carbohydrates': 4.3, 'fat': 0.2},
            {'name': '佛手瓜', 'category': '蔬菜', 'calories': 16, 'protein': 0.9, 'carbohydrates': 3.8, 'fat': 0.1},
            {'name': '苦菊', 'category': '蔬菜', 'calories': 15, 'protein': 1.8, 'carbohydrates': 2.1, 'fat': 0.2},
            {'name': '空心菜', 'category': '蔬菜', 'calories': 20, 'protein': 2.2, 'carbohydrates': 3.9, 'fat': 0.3},
            {'name': '油麦菜', 'category': '蔬菜', 'calories': 12, 'protein': 1.4, 'carbohydrates': 1.5, 'fat': 0.4},
            {'name': '莴笋', 'category': '蔬菜', 'calories': 14, 'protein': 1.0, 'carbohydrates': 2.8, 'fat': 0.1},
            {'name': '芥菜', 'category': '蔬菜', 'calories': 24, 'protein': 2.0, 'carbohydrates': 4.7, 'fat': 0.4},
            {'name': '菜心', 'category': '蔬菜', 'calories': 19, 'protein': 1.3, 'carbohydrates': 4.2, 'fat': 0.2},
            {'name': '红薯叶', 'category': '蔬菜', 'calories': 28, 'protein': 2.3, 'carbohydrates': 5.9, 'fat': 0.2},
            {'name': '莲藕', 'category': '蔬菜', 'calories': 73, 'protein': 2.0, 'carbohydrates': 16.4, 'fat': 0.2},
            {'name': '荸荠', 'category': '蔬菜', 'calories': 61, 'protein': 1.2, 'carbohydrates': 14.2, 'fat': 0.2},
            {'name': '萝卜', 'category': '蔬菜', 'calories': 16, 'protein': 0.9, 'carbohydrates': 3.4, 'fat': 0.1},
            {'name': '白萝卜', 'category': '蔬菜', 'calories': 21, 'protein': 0.9, 'carbohydrates': 5.0, 'fat': 0.1},
            {'name': '青萝卜', 'category': '蔬菜', 'calories': 20, 'protein': 1.0, 'carbohydrates': 4.6, 'fat': 0.1},
            {'name': '芋头', 'category': '蔬菜', 'calories': 79, 'protein': 2.2, 'carbohydrates': 18.1, 'fat': 0.2},
            {'name': '莲子', 'category': '蔬菜', 'calories': 344, 'protein': 17.2, 'carbohydrates': 67.2, 'fat': 1.9},
            {'name': '百合', 'category': '蔬菜', 'calories': 162, 'protein': 3.2, 'carbohydrates': 38.8, 'fat': 0.1},
            {'name': '平菇', 'category': '蔬菜', 'calories': 20, 'protein': 2.0, 'carbohydrates': 4.6, 'fat': 0.3},
            {'name': '杏鲍菇', 'category': '蔬菜', 'calories': 31, 'protein': 1.3, 'carbohydrates': 8.3, 'fat': 0.1},
            {'name': '茶树菇', 'category': '蔬菜', 'calories': 279, 'protein': 23.1, 'carbohydrates': 60.0, 'fat': 3.3},

            # ============ 更多水果 ============
            {'name': '提子', 'category': '水果', 'calories': 43, 'protein': 0.5, 'carbohydrates': 10.3, 'fat': 0.2},
            {'name': '车厘子', 'category': '水果', 'calories': 46, 'protein': 1.1, 'carbohydrates': 10.2, 'fat': 0.2},
            {'name': '杨梅', 'category': '水果', 'calories': 28, 'protein': 0.8, 'carbohydrates': 6.7, 'fat': 0.2},
            {'name': '山竹', 'category': '水果', 'calories': 69, 'protein': 0.4, 'carbohydrates': 17.0, 'fat': 0.6},
            {'name': '榴莲', 'category': '水果', 'calories': 147, 'protein': 2.6, 'carbohydrates': 27.1, 'fat': 3.3},
            {'name': '椰子', 'category': '水果', 'calories': 241, 'protein': 4.0, 'carbohydrates': 31.3, 'fat': 12.1},
            {'name': '椰子水', 'category': '饮料', 'calories': 19, 'protein': 0.7, 'carbohydrates': 3.7, 'fat': 0.2},
            {'name': '牛油果', 'category': '水果', 'calories': 171, 'protein': 2.0, 'carbohydrates': 7.4, 'fat': 15.3},
            {'name': '无花果', 'category': '水果', 'calories': 59, 'protein': 1.5, 'carbohydrates': 12.9, 'fat': 0.1},
            {'name': '枇杷', 'category': '水果', 'calories': 39, 'protein': 0.8, 'carbohydrates': 9.3, 'fat': 0.2},
            {'name': '山楂', 'category': '水果', 'calories': 102, 'protein': 0.7, 'carbohydrates': 25.1, 'fat': 0.6},
            {'name': '杨桃', 'category': '水果', 'calories': 29, 'protein': 0.6, 'carbohydrates': 7.3, 'fat': 0.2},
            {'name': '李子', 'category': '水果', 'calories': 36, 'protein': 0.7, 'carbohydrates': 8.7, 'fat': 0.2},
            {'name': '杏', 'category': '水果', 'calories': 38, 'protein': 0.9, 'carbohydrates': 9.1, 'fat': 0.1},
            {'name': '枣', 'category': '水果', 'calories': 125, 'protein': 1.2, 'carbohydrates': 30.5, 'fat': 0.2},
            {'name': '红枣', 'category': '水果', 'calories': 276, 'protein': 3.2, 'carbohydrates': 67.8, 'fat': 0.5},
            {'name': '桂圆', 'category': '水果', 'calories': 273, 'protein': 5.0, 'carbohydrates': 65.0, 'fat': 0.2},
            {'name': '葡萄干', 'category': '水果', 'calories': 341, 'protein': 2.5, 'carbohydrates': 81.8, 'fat': 0.4},

            # ============ 更多坚果和种子 ============
            {'name': '南瓜子', 'category': '坚果', 'calories': 574, 'protein': 35.1, 'carbohydrates': 4.9, 'fat': 46.0},
            {'name': '西瓜子', 'category': '坚果', 'calories': 573, 'protein': 32.7, 'carbohydrates': 13.1, 'fat': 44.8},
            {'name': '芝麻', 'category': '坚果', 'calories': 517, 'protein': 19.1, 'carbohydrates': 24.0, 'fat': 46.1},
            {'name': '黑芝麻', 'category': '坚果', 'calories': 531, 'protein': 19.1, 'carbohydrates': 24.0, 'fat': 46.1},
            {'name': '亚麻籽', 'category': '坚果', 'calories': 534, 'protein': 18.3, 'carbohydrates': 28.9, 'fat': 42.2},
            {'name': '奇亚籽', 'category': '坚果', 'calories': 486, 'protein': 16.5, 'carbohydrates': 42.1, 'fat': 30.7},

            # ============ 调味料和酱料 ============
            {'name': '酱油', 'category': '调味料', 'calories': 63, 'protein': 5.6, 'carbohydrates': 10.1, 'fat': 0.1},
            {'name': '蚝油', 'category': '调味料', 'calories': 130, 'protein': 5.3, 'carbohydrates': 25.6, 'fat': 0.5},
            {'name': '番茄酱', 'category': '调味料', 'calories': 81, 'protein': 2.0, 'carbohydrates': 18.9, 'fat': 0.2},
            {'name': '沙拉酱', 'category': '调味料', 'calories': 724, 'protein': 1.3, 'carbohydrates': 8.7, 'fat': 78.9},
            {'name': '蛋黄酱', 'category': '调味料', 'calories': 680, 'protein': 1.5, 'carbohydrates': 15.0, 'fat': 70.0},
            {'name': '芝麻酱', 'category': '调味料', 'calories': 618, 'protein': 19.2, 'carbohydrates': 22.7, 'fat': 52.7},
            {'name': '花生酱', 'category': '调味料', 'calories': 594, 'protein': 22.5, 'carbohydrates': 23.4, 'fat': 50.0},
            {'name': '辣椒酱', 'category': '调味料', 'calories': 135, 'protein': 2.0, 'carbohydrates': 19.3, 'fat': 5.8},
            {'name': '豆瓣酱', 'category': '调味料', 'calories': 178, 'protein': 7.5, 'carbohydrates': 25.1, 'fat': 5.6},
            {'name': '甜面酱', 'category': '调味料', 'calories': 136, 'protein': 5.3, 'carbohydrates': 27.8, 'fat': 0.6},
            {'name': '白糖', 'category': '调味料', 'calories': 400, 'protein': 0, 'carbohydrates': 100.0, 'fat': 0},
            {'name': '蜂蜜', 'category': '调味料', 'calories': 321, 'protein': 0.4, 'carbohydrates': 82.0, 'fat': 0},
            {'name': '枫糖浆', 'category': '调味料', 'calories': 260, 'protein': 0, 'carbohydrates': 67.0, 'fat': 0.2},

            # ============ 更多饮品 ============
            {'name': '奶茶', 'category': '饮料', 'calories': 60, 'protein': 0.8, 'carbohydrates': 10.9, 'fat': 1.6},
            {'name': '果茶', 'category': '饮料', 'calories': 42, 'protein': 0.1, 'carbohydrates': 10.5, 'fat': 0},
            {'name': '柠檬水', 'category': '饮料', 'calories': 6, 'protein': 0.1, 'carbohydrates': 1.6, 'fat': 0},
            {'name': '运动饮料', 'category': '饮料', 'calories': 26, 'protein': 0, 'carbohydrates': 6.3, 'fat': 0},
            {'name': '椰汁', 'category': '饮料', 'calories': 51, 'protein': 0.6, 'carbohydrates': 6.6, 'fat': 2.3},
            {'name': '红糖水', 'category': '饮料', 'calories': 389, 'protein': 0.7, 'carbohydrates': 96.6, 'fat': 0.2},
            {'name': '豆花', 'category': '豆制品', 'calories': 15, 'protein': 1.9, 'carbohydrates': 0.8, 'fat': 0.8},

            # ============ 快餐和西餐 ============
            {'name': '汉堡', 'category': '快餐', 'calories': 295, 'protein': 17.0, 'carbohydrates': 26.0, 'fat': 13.8},
            {'name': '披萨', 'category': '快餐', 'calories': 266, 'protein': 11.0, 'carbohydrates': 33.0, 'fat': 10.4},
            {'name': '热狗', 'category': '快餐', 'calories': 290, 'protein': 10.4, 'carbohydrates': 24.3, 'fat': 17.6},
            {'name': '炸鸡', 'category': '快餐', 'calories': 279, 'protein': 18.0, 'carbohydrates': 15.3, 'fat': 17.0},
            {'name': '薯条', 'category': '快餐', 'calories': 312, 'protein': 3.4, 'carbohydrates': 41.4, 'fat': 15.0},
            {'name': '三明治', 'category': '快餐', 'calories': 226, 'protein': 10.8, 'carbohydrates': 25.8, 'fat': 8.6},
            {'name': '寿司', 'category': '快餐', 'calories': 150, 'protein': 7.0, 'carbohydrates': 24.0, 'fat': 2.5},
            {'name': '牛排', 'category': '快餐', 'calories': 271, 'protein': 17.8, 'carbohydrates': 0, 'fat': 22.0},
            {'name': '意面', 'category': '快餐', 'calories': 158, 'protein': 5.8, 'carbohydrates': 30.9, 'fat': 0.9},
        ]

        created_count = 0
        for food_data in foods_data:
            food, created = FoodItem.objects.get_or_create(
                name=food_data['name'],
                defaults=food_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'创建食物: {food.name}'))

        self.stdout.write(self.style.SUCCESS(f'完成! 共创建 {created_count} 个食物'))
