# Generated by Django 5.1.7 on 2025-06-08 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('height', models.FloatField(default=0.0, help_text='单位为厘米', verbose_name='身高 (cm)')),
                ('weight', models.FloatField(default=0.0, help_text='单位为千克', verbose_name='体重 (kg)')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('information', models.TextField(blank=True, verbose_name='个人简介')),
                ('target', models.TextField(blank=True, verbose_name='当前目标')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
