# Generated by Django 5.1.7 on 2025-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='information',
        ),
        migrations.AddField(
            model_name='information',
            name='dietGoal',
            field=models.TextField(blank=True, verbose_name='当前饮食目标'),
        ),
        migrations.AddField(
            model_name='information',
            name='exerciseTime',
            field=models.TextField(blank=True, verbose_name='当前锻炼时间'),
        ),
        migrations.AddField(
            model_name='information',
            name='exerciseType',
            field=models.TextField(blank=True, verbose_name='当前目标'),
        ),
        migrations.AddField(
            model_name='information',
            name='foodType',
            field=models.TextField(blank=True, verbose_name='当前饮食类型'),
        ),
        migrations.AddField(
            model_name='information',
            name='mealTime',
            field=models.TextField(blank=True, verbose_name='当前饮食时间'),
        ),
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.IntegerField(default=21, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='information',
            name='height',
            field=models.FloatField(default=170.0, help_text='单位为厘米', verbose_name='身高 (cm)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='target',
            field=models.TextField(blank=True, verbose_name='当前锻炼目标'),
        ),
        migrations.AlterField(
            model_name='information',
            name='weight',
            field=models.FloatField(default=55.0, help_text='单位为千克', verbose_name='体重 (kg)'),
        ),
    ]
