# Generated by Django 5.1.7 on 2025-10-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_remove_information_dietgoal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别'),
        ),
    ]
