# Generated by Django 5.1.7 on 2025-10-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_information_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='target_calories',
            field=models.FloatField(blank=True, help_text='用户自定义的每日目标热量，如果未设置则使用系统计算值', null=True, verbose_name='每日目标热量(kcal)'),
        ),
    ]
