# Generated by Django 5.1.7 on 2025-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('thing', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('day', models.IntegerField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
