# Generated by Django 5.1.7 on 2025-06-08 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name': '周常计划', 'verbose_name_plural': '周常计划'},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='day',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='thing',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='username',
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期日')], default=1, verbose_name='星期几'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='计划标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
