# Generated by Django 5.1.7 on 2025-06-08 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_options_remove_plan_day_remove_plan_thing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='详细描述'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='end_time',
            field=models.TimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_time',
            field=models.TimeField(verbose_name='开始时间'),
        ),
    ]
