# Generated by Django 5.1.7 on 2025-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_plan_user_alter_plan_description_alter_plan_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
